#!/bin/sh

sleep 0.5
pactl set-sink-port alsa_output.pci-0000_00_1f.3.analog-stereo analog-output-headphones || audiofix
pactl set-sink-port alsa_output.pci-0000_00_1f.3.analog-stereo analog-output-lineout 
