#!/bin/sh
scriptname="bluelighter"
scriptdisc="script for applying bluelight using sct on xorg"
source zconf

bluelight=3500
bluelight=3000
bluelight=2500


SCTSTATE_PATH=/tmp/bluelighter-state

sctstate=$([ -f "$SCTSTATE_PATH" ] && cat "$SCTSTATE_PATH" || echo 0)


if [ "$sctstate" = '0' ]; then
sct "$bluelight"
else
sct 0
fi
sctstate=$((!$sctstate)); echo $sctstate > $SCTSTATE_PATH 
