#!/bin/sh
startup=0
if [ $startup = 0 ]
then
	/opt/Ibin/scripts/dwm-statustray.sh & 
	/opt/Ibin/scripts/lock.sh & 
	~/.fehbg &
fi
# relaunch DWM if the binary changes, otherwise bail
csum=""
new_csum=$(sha1sum $(which dwm))
while true
do
    if [ "$csum" != "$new_csum" ]
    then
        csum=$new_csum
        dwm
    else
        exit 0
    fi
    new_csum=$(sha1sum $(which dwm))
    sleep 0.5
done
