#!/bin/sh
startup=0
if [ $startup = 0 ]
then
	/opt/Ibin/scripts/dwm-statustray.sh & 
	/opt/Ibin/scripts/lock.sh & 
	~/.fehbg &
fi
# relaunch DWM if the binary changes, otherwise bail
csum=""
new_csum=$(sha1sum $(which dwm))
while true
do
    if [ "$csum" != "$new_csum" ]
    then
        csum=$new_csum
        dwm
    else

	#dwm
	choice=$(echo "Cancel\ni3\nquit" | dmenu)
	case "$choice" in
		"Cancel") dwm ;;
		"i3") i3 ;;
		"quit") exit ;;
	esac
#run script




       # exit 0
    fi
    new_csum=$(sha1sum $(which dwm))
    sleep 0.5
done
