#!/bin/sh

scriptname="launch script"
scriptdisc='script to launch programs in $PATH with extras'
. zconf


addoptions(){
EXTRAOPTIONS="$EXTRAOPTIONS\n$1"
}
# if you want to you can add something like ". $HOME/.config/launchscript.conf" and have a shell script there that has the func "prechoice" and "postchoice" to make a config file insted of editting the shell script it's self
prechoice(){
addoptions "skype"
addoptions "discord"
}
postchoice(){
launchexcept "heroic" "heroic --ozone-platform-hint=auto $arg2"
launchexcept "signal-desktop" "signal-desktop --ozone-platform-hint=auto $arg2"
launchexcept "ripcord" "env QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/qt/plugins ripcord $arg2"
launchexcept "steam" "env SDL_VIDEODRIVER=x11 steam $arg2"
launchexcept "discord" "$BROWSER www.discord.com/app"
launchexcept "skype" "$BROWSER web.skype.com"
}
if [ -z "$BROWSER" ]
then
	BROWSER="firefox"
fi

prechoice
test="$({ set -f; IFS=:; for d in $PATH; do set +f; [ -n "$d" ] || d=.; for f in "$d"/.[!.]* "$d"/..?* "$d"/*; do [ -f "$f" ] && [ -x "$f" ] && printf '%s\n' "${f##*/}"; done; done; })"
launch="$(printf "$test\n$EXTRAOPTIONS" | sort | "$@")"

set -- $launch
arg1=($launch)
if [ "$#" != "1" ]
then
x="$launch"
arg2="${x#* }"
arg2="${x#* }"
#else
#arg2="arg2 not set"
fi

echo "launch=$launch"
echo "arg1=$arg1"
echo "arg2=$arg2"

launchexcept(){
if [ "$arg1" = "$1" ]
then
	nohup $2 > /dev/null 2>&1&
	exit
fi
}
postchoice
nohup "$launch" > /dev/null 2>&1&
