#!/bin/sh

scriptname="launch script"
scriptdisc='script to launch programs in $PATH with extras'
source zconf




test="$({ set -f; IFS=:; for d in $PATH; do set +f; [ -n "$d" ] || d=.; for f in "$d"/.[!.]* "$d"/..?* "$d"/*; do [ -f "$f" ] && [ -x "$f" ] && printf '%s\n' "${f##*/}"; done; done; } | sort)"
launch="$(echo "$test" | "$@")"

set -- $launch
arg1=($launch)
if [ "$#" != "1" ]
then
x="$launch"
arg2="${x#* }"
arg2="${x#* }"
#else
#arg2="arg2 not set"
fi

echo "launch=$launch"
echo "arg1=$arg1"
echo "arg2=$arg2"


case "$arg1" in
  heroic)
    heroic --ozone-platform-hint=auto $arg2 & disown;;
  signal-desktop)
    signal-desktop --ozone-platform-hint=auto $arg2 & disown;;
  ripcord)
    env QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/qt/plugins ripcord $arg2 & disown;;
  steam)
    env SDL_VIDEODRIVER=x11 steam $arg2 & disown;;
  *)
    $launch & disown
    ;;
esac

