#!/bin/sh

scriptname="launch script"
scriptdisc='script to launch programs in $PATH with extras'
. zconf

test="$({ set -f; IFS=:; for d in $PATH; do set +f; [ -n "$d" ] || d=.; for f in "$d"/.[!.]* "$d"/..?* "$d"/*; do [ -f "$f" ] && [ -x "$f" ] && printf '%s\n' "${f##*/}"; done; done; } | sort)"
launch="$(echo "$test" | "$@")"

set -- $launch
arg1=($launch)
if [ "$#" != "1" ]
then
x="$launch"
arg2="${x#* }"
arg2="${x#* }"
#else
#arg2="arg2 not set"
fi

echo "launch=$launch"
echo "arg1=$arg1"
echo "arg2=$arg2"

launchexcept(){
if [ "$arg1" = "$1" ]
then
	notify-send "running" "$2"
	nohup "$2" > /dev/null 2>&1
	exit
fi
}
launchexcept "herotic" "heroic --ozone-platform-hint=auto $arg2"
launchexcept "signal-desktop" "signal-desktop --ozone-platform-hint=auto $arg2"
launchexcept "ripcord" "env QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/qt/plugins ripcord $arg2"
launchexcept "steam" "env SDL_VIDEODRIVER=x11 steam $arg2"
nohup $launch > /dev/null 2>&1&
