#!/bin/sh
. zconf
mullvadcli="mullvad"
menu="bemenu"

mullvadloop(){ 
if [ "$mullvadlooped" = "1" ]
then
	sleep 1
fi
mullvadlooped=1
mullvadacount="$($mullvadcli account get)"
if [ "$mullvadacount" = "Not logged in on any account" ]
then
	option="login"
else
mullvadstatus="$($mullvadcli status)"
toggleconnect="connect
disconnect"
if [ "$mullvadstatus" = "Disconnected" ]
then
	toggleconnect="connect"
else
	toggleconnect="disconnect
reconnect"
fi
option="$(echo "$toggleconnect
set locale
logout
exit" |  $menu -p "mullvad status '$mullvadstatus'" )"
fi
case $option in

 disconnect)
    $mullvadcli disconnect && mullvadloop
    ;;

  reconnect)
    $mullvadcli reconnect && mullvadloop
    ;;
 connect)
    $mullvadcli connect && mullvadloop
    ;;
 "set locale")
        mullvadrelaylistcodes="$($mullvadcli relay list | awk '!/^\t\t.*$/' | awk '/./' | sed 's/ @.*//g' | sed 's/^\t/ ∙ /g' | awk '{print (substr($0,length($0)-3,3))}' | sed 's/(//g' )"
	$mullvadcli relay set location "$(echo "$mullvadrelaylistcodes" | $menu)" && mullvadloop
	;;
 login)
	$mullvadcli account login "$(echo "" | $menu -p "enter login number" )" && mullvadloop 
    ;;
 logout)
	 $mullvadcli account logout && mullvadloop
	 ;;
 exit)
	 exit
	 ;;

  *)
    echo -n "error command unknown"
    ;;
esac
}
mullvadloop
