#!/bin/sh
scriptname="pacman update script"
scriptdisc="script to update pacman and aurutils and others"
source zconf


sudo pacman -Sy archlinux-keyring --needed --noconfirm
#sudo pacman -Syu
sudo pacman -Su


#command -v "aur" > /dev/null 2>&1 && aur=true
#if [ -n "$aur" ]
if command -v aur > /dev/null 2>&1
then
	echo "$(tput setaf 4):: $(tput sgr0)Syncing aur..."
        aur sync -u
fi

if command -v flatpak > /dev/null 2>&1
then
	echo "$(tput setaf 4):: $(tput sgr0)updating flatpaks..."
        flatpak update
fi
