#!/bin/sh
scriptname="pacman update script"
scriptdisc="script to update pacman and aurutils and others"
source zconf


sudo pacman -Sy archlinux-keyring --needed --noconfirm
#sudo pacman -Syu
sudo pacman -Su
echo "$(tput setaf 4):: $(tput sgr0)Syncing aur..."
aur sync -u
