#!/usr/bin/bash
if pgrep "picom"
then
	notify-send "killing picom"
	pkill picom 
	set -- $(xprop -root _NET_ACTIVE_WINDOW)
	windowid="$5"
	xprop -spy -id "$windowid"
	notify-send "closed restarting picom"
	picom & disown
else
	notify-send "picom not running"
fi
