#!/bin/bash
latesturi="https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases/latest"
steam="$HOME/.steam/root/compatibilitytools.d"
proton="$(curl -s $latesturi | grep "browser_download_url.*Proton.*tar.gz" | cut -d \" -f4)"
protonlist="$(find "$steam" -name "GE-Proton*" -type d -print)"
protonver="$(echo "$proton" | cut -f8 -d\/)"
installed="$(find "$steam" -name "GE-Proton*" -type d -print | cut -f7 -d/)"
if [ "$(echo "$installed" | grep "$protonver")" ]
then
	echo "newist proton ver installed"
	echo "exiting"
	exit
fi

if [ -n "$1" ] && [ -z "$protondelete" ]
then
	protondelete="$1"
fi


echo "Currently installed Proton-GE version/s $protonlist will be removed and updated."
echo
echo "Waiting for 3 seconds before proceeding with update ..."
sleep 3

# Create and switch to temporary directory
cd "$(mktemp -d)" 

# Delete currently installed proton-ge
if [ "$protondelete" = "1" ]
then
echo "Deleting $protonlist"
rm -rf "$protonlist"
echo "Old Proton-GE version/s successfully removed."
echo
else
	echo "proton delete skiped"
fi
# Download latest proton-ge
wget "$proton"

# Extract tarball to Steam directory
mkdir -p "$steam"
echo "Created directory $steam"
tar -xf *.tar.gz -C "$steam"

# Delete temporary directory
echo "Deleting temporary directory $(pwd)"
rm -rf "$(pwd)"

echo "Please restart Steam."
echo
echo "DONE"
