#!/bin/sh
mouseid="cheering-viscacha"

#how to use.
#step 1 add to your wm/de
#mutiable keybinds something like "leftalt + leftwinkey + number" for every number between 1-9 and make the keybind launch with script with the arg profile[num] were [num] is the same as the number used in the bind
#then make sure the "macro +KEY_LEFTALT +KEY_LEFTMETA KEY_2 -KEY_LEFTALT -KEY_LEFTMETA" are formated the same as the binds
#then run the shortcut and button 5 on your mouse should sycle profiles writen bellow on the mouse 


#Button: 0 is mapped to 'button 1' left mouse
#Button: 1 is mapped to 'button 2' right mouse
#Button: 2 is mapped to 'button 3' middle mouse
#Button: 3 is mapped to 'button 4' side top
#Button: 4 is mapped to 'button 5' side bottom

defaultprofile() {
notify-send "loading defaults"
ratbagctl "$mouseid" button 0 action set button 1
ratbagctl "$mouseid" button 1 action set button 2
ratbagctl "$mouseid" button 2 action set button 3
ratbagctl "$mouseid" button 3 action set button 4
ratbagctl "$mouseid" button 4 action set button 5
}

profile1() {
defaultprofile
notify-send "profile switch 1"
ratbagctl "$mouseid" button 5 action set macro +KEY_LEFTALT +KEY_LEFTMETA KEY_2 -KEY_LEFTALT -KEY_LEFTMETA
}
profile2() {
defaultprofile
notify-send "profile switch 2"
ratbagctl "$mouseid" button 0 action set macro KEY_J
ratbagctl "$mouseid" button 1 action set macro KEY_K
ratbagctl "$mouseid" button 5 action set macro +KEY_LEFTALT +KEY_LEFTMETA KEY_1 -KEY_LEFTALT -KEY_LEFTMETA
}
$1
