#!/bin/bash

SHOWNAME_PATH=~/.cache/block-mpd-showname

exec-mpc() {
    mpc $* &> /dev/null
}

showname=$([ -f $SHOWNAME_PATH ] && cat $SHOWNAME_PATH || echo 0)

case $BLOCK_BUTTON in
  1) exec-mpc toggle ;;
  2) exec-mpc stop   ;;
  3) showname=$((!$showname)); echo $showname > $SHOWNAME_PATH ;;
  4) exec-mpc pre    ;;
  5) exec-mpc next   ;;
esac

playing=⏸
#paused=⏵
paused=⏯
stopped=🔽
#stopped=♪

if [ $showname = '1' ]; then
  mpc current | awk -F ' - ' '{printf "【%s】", substr($2, 0, 20)}'
fi

status=$(mpc status | sed -n 's/^\[\([^])]*\)\].*$/\1/p')
case $status in
  playing) echo -n $playing ;;
  paused)  echo -n $paused  ;;
  *)       echo -n $stopped ;;
esac

