#!/bin/sh
# Loop from var-var.
start=0
if [ -z "$1" ]
then
	printf "no time set"
	exit
fi
end=$1
sec=-1
secmax=$sec
startmax=$start
secman=$sec
while [ "$startmax" -le "$end" ]; do
    startmax=$((startmax+1))
    secmax=$(($secmax+1))
    if [ "$secmax" = 60 ]
    then
	    secmax=0
	    minmax=$(($minmax+1))
    fi
    printf "loop"
done
if [ "$secmax" = 0 ]
then
    endprint="$minmax min"
elif [ -z "$minmax" ]
then
	endprint="$secmax sec"
else
	endprint="$minmax min $secmax sec"
fi



while [ "$start" -le "$end" ]; do
    start=$((start+1))
    sec=$(($sec+1))
    clear
    if [ "$sec" = 60 ]
    then
	    sec=0
	    min=$(($min+1))
    startprint="$min min"
    elif [ -z "$min" ]
    then
    startprint="$sec sec"
    else
    startprint="$min min $sec sec"
    fi
    printf '%s\n' "$startprint / $endprint"
    sleep 1
done
mpv --no-video "$HOME/Music/ringtone/All Might - a phone call is here.wav"
