#!/bin/sh
if [ -z "$1" ]
then
	MENU="fzf"
else
	MENU="$1"
fi
#file_data="$(<"file")"
steamvdfdir="$HOME/.local/share/Steam/steamapps/libraryfolders.vdf"
steamvdf="$(cat $steamvdfdir)"

steamvdfget(){
file="$1"
while IFS= read -r line || [ -n "$line" ]
do
    set -- $line
    #printf '%s\n' "$1"
    #printf '%s\n' "$2"
    if [ "$1" = '"path"' ]
    then
    var=${2:1:-1}
    printf '%s\n' "$var"
    fi
done < "$file"
}
STEAMDIRS="$(steamvdfget $steamvdfdir )"
TABLE=""
for STEAM in $STEAMDIRS; do
echo "loop STEAMDIR"
STEAMAPPS="$STEAM/steamapps"
for file in "$STEAMAPPS"/*.acf
do
	filecon=$(cat "$file")
    ID=$(echo "$filecon" | grep '"appid"' | head -1 | sed -r 's/[^"]*"appid"[^"]*"([^"]*)"/\1/' )
    NAME=$(echo "$filecon" | grep '"name"' | head -1 | sed -r 's/[^"]*"name"[^"]*"([^"]*)"/\1/' )
    TABLE="$TABLE \n$NAME \n$ID"
done
done

TABLE="$(echo "$TABLE" | tr '[:upper:]' '[:lower:]')"

steamname="$(printf "$TABLE" | sed '1~2d' | sort | $MENU)"
#steamname="$(printf "$TABLE" | sed '1~2d' | fzf)"


if [ -n "$steamname" ]
then

steamid="$(printf "$TABLE" | grep -wA1 "$steamname" | grep -vw "$steamname")"

steam steam://rungameid/$steamid
fi
