#!/bin/sh
if [ -z "$1" ]
then
	MENU="fzf"
else
	MENU="$1"
fi
steamvdfdir="$HOME/.local/share/Steam/steamapps/libraryfolders.vdf"


steamvdfget(){
file="$1"
while IFS= read -r line || [ -n "$line" ]
do
    set -- $line
    if [ "$1" = '"path"' ]
    then
    var=${2:1:-1}
    printf '%s\n' "$var"
    fi
done < "$file"
}

STEAMDIRS="$(steamvdfget $steamvdfdir )"
TABLE=""
for STEAM in $STEAMDIRS; do
STEAMAPPS="$STEAM/steamapps"
for file in "$STEAMAPPS"/*.acf
do
while IFS= read -r line || [ -n "$line" ]
do
    set -- $line
    if [ "$1" = '"name"' ]
    then
	shift
	var="$*"
    	var=${var:1:-1}
	NAME="$var"

    fi
    set -- $line
    if [ "$1" = '"appid"' ]
    then
	shift
	var="$*"
    	var=${var:1:-1}
    ID="$var"
    fi
done < "$file"
TABLE="$TABLE \n$NAME \n$ID"
done
done

TABLE="$(echo "$TABLE" | tr '[:upper:]' '[:lower:]')"
steamname="$(printf "$TABLE" | sed '1~2d' | sort | $MENU)"

if [ -n "$steamname" ]
then

steamid="$(printf "$TABLE" | grep -wA1 "$steamname" | grep -vw "$steamname")"

steam steam://rungameid/$steamid
fi
