#!/bin/sh
arg1="$1"
arg2="$2"
argnum="$#"
if [ "$arg1" = "-u" ]
then
	user="$arg2"
	shift
	shift
else
	user="root"
fi
args="$*"

if [ -n "$args" ]
then
	su "$user" -c "$args"
	echo "running as su"
else
	echo "no command"
fi
