#!/bin/sh
scriptname="update script"
scriptdisc="script to update all things"
. zconf



#UPDATETHEME="$(tput setaf 4):: $(tput sgr0)"
UPDATETHEME="$(tput setaf 2)==> $(tput sgr0)"

if [ -z "$ROOTTOOL" ]
then
ROOTTOOL="sudo"
fi

cargoupdate(){
	cargo install $(cargo install --list | grep -E '^[a-z0-9_-]+ v[0-9.]+:$' | cut -f1 -d' ')
	#cargo install $(notify-send "cargo install run")
}
pacmanupdate(){
$ROOTTOOL pacman -Sy archlinux-keyring --needed --noconfirm
$ROOTTOOL pacman -Su
}

aptupdate(){
$ROOTTOOL apt update
$ROOTTOOL apt uprade
}


checkupdate(){
if command -v "$1" > /dev/null 2>&1
then
	if [ -n "$3" ]
	then
	echo "$UPDATETHEME$3"
	#echo "$(tput setaf 4):: $(tput sgr0)$3"
	fi
	$2
fi
}
#checkupdate "yay" "yay" "Starting yay upgrade"
#checkupdate "paru" "paru" "Starting paru upgrade"
checkupdate "pacman" "pacmanupdate" "Starting pacman upgrade"
checkupdate "apt" "aptupdate" "Starting apt upgrade"
checkupdate "dnf" "$ROOTTOOL dnf upgrade" "Starting dnf upgrade"
checkupdate "aur" "aur sync -u" "Syncthing aur..."
checkupdate "flatpak" "flatpak update" "updating flatpaks..."
#checkupdate "snap" "sudo snap refresh" "updating snaps..."
checkupdate "cargo" "cargoupdate" "updating crates..."
