#!/bin/sh
startup=0
wm='dwm'
wm="$1"
if ! [ $startup = 0 ]
then
	/opt/Ibin/scripts/dwm-statustray.sh & 
	/opt/Ibin/scripts/lock.sh & 
	~/.fehbg &
fi
echo "#this is a file for keeping track of dynamic scratchpads" > ~/.scratchpad/dynamic/dynamic
# relaunch DWM if the binary changes, otherwise bail



if [ "$cmus_use" = "" ] 
then
	while true
	do
	$wm
	done
else



csum=""
new_csum=$(sha1sum $(which $wm))
while true
do
    if [ "$csum" != "$new_csum" ]
    then
        csum=$new_csum
        $wm
    else
	#$wm
	choice=$(echo "Cancel\ni3\nawesome\nquit" | dmenu)
	case "$choice" in
		"Cancel") $wm ;;
		"i3") i3 ;;
		"awesome") awesome ;;
		"quit") exit ;;
	esac
#run script




       # exit 0
    fi
    new_csum=$(sha1sum $(which $wm))
    sleep 0.5
done
fi
