#!/bin/sh

mon="$1"
if [ "$2" ]
then
pos="$2"
else
pos="--right-of DP-0"
fi
monargs="--auto $pos"
if xrandr | grep "mm x " | grep "$mon connected"
then
xrandr --output "$mon" --off
else
xrandr --output "$mon" $monargs
fi
xsetroot -cursor_name left_ptr
