#!/bin/sh
arg1="$1"
if ! [ "$arg1" = "auto" ]
then
xprop -f WM_STATE 32c -set WM_STATE 1
else
xwin="$(xprop -root _NET_ACTIVE_WINDOW | grep -o "[^ ]*$")"
xprop -id "$xwin" -f WM_STATE 32c -set WM_STATE 1
fi
