#!/bin/sh



# config
STEAM_SDL_VIDEODRIVER="X11"




if [ -z "$WAYLAND_DISPLAY" ]
then
	dmenu="dmenu"
else
	dmenu="bemenu"
	wayland=1
fi

arg="$1"


# add --help to all scripts
if [ "$arg" = "--help" ] || [ "$arg" = "-h" ] 
then
	echo "-- help --"
	echo "$scriptname"
	if [ -n "$scriptdisc" ]
	then
		echo "-- discript --"
		echo "$scriptdisc"
	fi
	if [ -n "$scriptreq" ]
	then
		echo "-- scriptreq --"
		echo "$scriptreq"
	fi
	exit
fi
