#!/bin/sh



# config
#STEAM_SDL_VIDEODRIVER=""




if [ -z "$WAYLAND_DISPLAY" ]
then
	#dmenu="dmenu"
	dmenu="bemenu"
else
	dmenu="bemenu"
	wayland=1
fi

#arg="$1"
#args="$@"


# add --help to all scripts
if [ "$arg" = "--help" ] || [ "$arg" = "-h" ] 
then
	echo "-- help --"
	echo "$scriptname"
	if [ -n "$scriptdisc" ]
	then
		echo "-- discript --"
		echo "$scriptdisc"
	fi
	if [ -n "$scriptreq" ]
	then
		echo "-- scriptreq --"
		echo "$scriptreq"
	fi
	exit
fi
