#!/bin/sh
scriptname="zukice"
scriptdisc="script to freeze xorg programs"
source zconf


pid="$(set -- $(xprop -id "$(set -- $(xprop -root _NET_ACTIVE_WINDOW); echo "$5")" _NET_WM_PID); echo "$3")"
set -- $(ps -p "$pid" -o stat)
echo "$2"
if [ "$2" = "Tl" ] || [ "$2" = "T<l" ] || [ "$2" = "T" ]
then
	#notify-send 'kill -CONT "$pid"'
	kill -CONT "$pid"
else
	#notify-send 'kill -STOP "$pid"'
	kill -STOP "$pid"
fi
